# Generated by Django 4.1 on 2022-08-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="queue",
            name="updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
